### ISSUE TITLE
current day shows different times in different sections

### ISSUE THREAD

**Issue by huehnerlady** [timesheetIO/android-api#7]
Hi,

I really like timesheet io. But the summary for underneath the current Timer seems to add the breaks again instead of subtracting them:
As you can see in the picture below, there are 4 times in different sections. 
MY opinion is, that they should all show the same, but (from top to bottom):
work-time `4:12`, break-time `0:12`
1. the notification bar shows the whole time - including the break (`4:24`)
2. the time at the timer shows the correct value - the time worked - excluding the break (`4:12`)
3. The time in the summary (TOTAL) seems to show the total time (as in 1.) but with the break again added on. (`4:36`)
4. the bottom most filter shows `00h 00m`

![2018-08-16 12 00 35](https://user-images.githubusercontent.com/12533979/44202357-0481c500-a14c-11e8-99c7-661dbc244e25.jpg)

Is there any plan on fixing this? 
I really like this app, but all these different times are really confusing...

**Comment by FlorianRauscha** [comment]
Thank you for the report. This issue will be fixed in version 2.6.0.
